### ISSUE TITLE
API not reachable

### ISSUE THREAD

**Issue by 0xr22** [steamcmd/api#30]
Hi,

I'm trying to use the public api (https://api.steamcmd.net/v2/info/730 & https://api.steamcmd.net/v1/version) but I'm getting an application error from heroku. May you fix the api? 😄 

Best regards
0x22

**Comment by jonakoudijs** [comment]
Hi 0x22,

Sadly the API is still a bit unstable and one once a month the Redis connection (for caching) disables automatically because of a bug. I fixed this manually and hopefully I have some more time in May to fix this particular bug.

Meanwhile I started on the basis for a complete rewrite which should improve the stability a lot.

Greeting,
Jona
